//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafireHub.DataCollectionWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessDataDTO", Namespace="http://schemas.datacontract.org/2004/07/MES.AMS.MeiShanMES.BigScreen.Machines.DTO" +
        "")]
    [System.SerializableAttribute()]
    public partial class ProcessDataDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CollectionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EquimentNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParameterCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParameterNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParameterValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParameterZh_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcessCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcessNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProcessZh_NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CollectionDate {
            get {
                return this.CollectionDateField;
            }
            set {
                if ((object.ReferenceEquals(this.CollectionDateField, value) != true)) {
                    this.CollectionDateField = value;
                    this.RaisePropertyChanged("CollectionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EquimentNum {
            get {
                return this.EquimentNumField;
            }
            set {
                if ((object.ReferenceEquals(this.EquimentNumField, value) != true)) {
                    this.EquimentNumField = value;
                    this.RaisePropertyChanged("EquimentNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParameterCode {
            get {
                return this.ParameterCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ParameterCodeField, value) != true)) {
                    this.ParameterCodeField = value;
                    this.RaisePropertyChanged("ParameterCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParameterName {
            get {
                return this.ParameterNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ParameterNameField, value) != true)) {
                    this.ParameterNameField = value;
                    this.RaisePropertyChanged("ParameterName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParameterValue {
            get {
                return this.ParameterValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ParameterValueField, value) != true)) {
                    this.ParameterValueField = value;
                    this.RaisePropertyChanged("ParameterValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParameterZh_Name {
            get {
                return this.ParameterZh_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.ParameterZh_NameField, value) != true)) {
                    this.ParameterZh_NameField = value;
                    this.RaisePropertyChanged("ParameterZh_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProcessCode {
            get {
                return this.ProcessCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessCodeField, value) != true)) {
                    this.ProcessCodeField = value;
                    this.RaisePropertyChanged("ProcessCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProcessName {
            get {
                return this.ProcessNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessNameField, value) != true)) {
                    this.ProcessNameField = value;
                    this.RaisePropertyChanged("ProcessName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProcessZh_Name {
            get {
                return this.ProcessZh_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProcessZh_NameField, value) != true)) {
                    this.ProcessZh_NameField = value;
                    this.RaisePropertyChanged("ProcessZh_Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataCollectionWebService.EquipmentDataService")]
    public interface EquipmentDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EquipmentDataService/SaveNewProcessData", ReplyAction="http://tempuri.org/EquipmentDataService/SaveNewProcessDataResponse")]
        bool SaveNewProcessData(SafireHub.DataCollectionWebService.ProcessDataDTO processDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EquipmentDataService/SaveNewProcessData", ReplyAction="http://tempuri.org/EquipmentDataService/SaveNewProcessDataResponse")]
        System.Threading.Tasks.Task<bool> SaveNewProcessDataAsync(SafireHub.DataCollectionWebService.ProcessDataDTO processDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EquipmentDataService/test", ReplyAction="http://tempuri.org/EquipmentDataService/testResponse")]
        string test();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EquipmentDataService/test", ReplyAction="http://tempuri.org/EquipmentDataService/testResponse")]
        System.Threading.Tasks.Task<string> testAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EquipmentDataServiceChannel : SafireHub.DataCollectionWebService.EquipmentDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EquipmentDataServiceClient : System.ServiceModel.ClientBase<SafireHub.DataCollectionWebService.EquipmentDataService>, SafireHub.DataCollectionWebService.EquipmentDataService {
        
        public EquipmentDataServiceClient() {
        }
        
        public EquipmentDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EquipmentDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EquipmentDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EquipmentDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SaveNewProcessData(SafireHub.DataCollectionWebService.ProcessDataDTO processDate) {
            return base.Channel.SaveNewProcessData(processDate);
        }
        
        public System.Threading.Tasks.Task<bool> SaveNewProcessDataAsync(SafireHub.DataCollectionWebService.ProcessDataDTO processDate) {
            return base.Channel.SaveNewProcessDataAsync(processDate);
        }
        
        public string test() {
            return base.Channel.test();
        }
        
        public System.Threading.Tasks.Task<string> testAsync() {
            return base.Channel.testAsync();
        }
    }
}
